# RunPod Configuration - Force Source Code Deployment
[build]
python_version = "3.11"
cuda_version = "12.4"

[build.commands]
- "pip install -r requirements.serverless.txt"

[runtime]
handler = "handler.serverless.handler"
python_path = "."

[runtime.env]
PYTHONPATH = "."
PYTHONUNBUFFERED = "1"
CUDA_VISIBLE_DEVICES = "0"
TORCH_CUDA_ARCH_LIST = "8.9,9.0"